In [15]:
import tensorflow as tf
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

#### Import the Dataset

In [16]:
dataset = pd.read_csv('F:/Data_Set/iris.csv')  

In [17]:
dataset.head() 

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#### Divide dataset into dependent and independent variable

In [18]:
x = dataset.iloc[:,0:4].values 

In [19]:
print(x) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [20]:
y = dataset.iloc[:,-1].values  

In [21]:
print(y)   

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

#### Convert categorical data into numerical

In [9]:
#from sklearn.preprocessing import OneHotEncoder 
#from sklearn.model_selection import Linearregression  

In [22]:
import keras 
from keras.models import Sequential
from keras.layers import Dense 
from keras.optimizers import Adam
import pydot 
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot  
from keras.utils import plot_model 
import seaborn as sns 

#### Convert categorical data into numerical form

In [23]:
from sklearn.preprocessing import LabelEncoder 

In [10]:
#dataset 

In [24]:
encoder = LabelEncoder()
y = encoder.fit_transform(y) 
y = pd.get_dummies(y).values 

In [47]:
#print(y) 

 #### Dividing the dataset into traning set and test set

In [25]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)  

#### Create ANN Layers

In [27]:
model = Sequential() 

In [28]:
model.add(Dense(4,input_shape=(4,),activation='relu')) 

In [29]:
model.add(Dense(3,activation='softmax')) 

#### Model Compile 

In [33]:
model.compile(optimizer = 'Adam',loss='categorical_crossentropy',metrics = ['accuracy']) 

#### Finel ephoc or traning stage

In [34]:
model.fit(x_train,y_train,batch_size=10,nb_epoch=100)  

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
120/120 [==============================] - 1s 9ms/step - loss: 1.1191 - accuracy: 0.3667
Epoch 2/100
120/120 [==============================] - 0s 217us/step - loss: 1.0436 - accuracy: 0.3667
Epoch 3/100
120/120 [==============================] - 0s 217us/step - loss: 0.9857 - accuracy: 0.3750
Epoch 4/100
120/120 [==============================] - 0s 200us/step - loss: 0.9369 - accuracy: 0.3917
Epoch 5/100
120/120 [==============================] - 0s 225us/step - loss: 0.9015 - accuracy: 0.5250
Epoch 6/100
120/120 [==============================] - 0s 258us/step - loss: 0.8765 - accuracy: 0.6500
Epoch 7/100
120/120 [==============================] - 0s 283us/step - loss: 0.8585 - accuracy: 0.6583
Epoch 8/100
120/120 [==============================] - 0s 242us/step - loss: 0.8474 - accuracy: 0.6667
Epoch 9/100
120/120 [==============================] - 0s 233us/step - loss: 0.8354 - accuracy: 0.6833
Epoch 10/100
120/120 [==============================] - 0s 233us/step - los

120/120 [==============================] - 0s 183us/step - loss: 0.3275 - accuracy: 0.9333
Epoch 80/100
120/120 [==============================] - 0s 192us/step - loss: 0.3241 - accuracy: 0.9333
Epoch 81/100
120/120 [==============================] - 0s 217us/step - loss: 0.3212 - accuracy: 0.9417
Epoch 82/100
120/120 [==============================] - 0s 192us/step - loss: 0.3192 - accuracy: 0.9250
Epoch 83/100
120/120 [==============================] - 0s 175us/step - loss: 0.3144 - accuracy: 0.9417
Epoch 84/100
120/120 [==============================] - 0s 217us/step - loss: 0.3114 - accuracy: 0.9417
Epoch 85/100
120/120 [==============================] - 0s 225us/step - loss: 0.3094 - accuracy: 0.9417
Epoch 86/100
120/120 [==============================] - 0s 250us/step - loss: 0.3059 - accuracy: 0.9417
Epoch 87/100
120/120 [==============================] - 0s 317us/step - loss: 0.3045 - accuracy: 0.9417
Epoch 88/100
120/120 [==============================] - 0s 225us/step - loss:

In [37]:
y_pred = model.predict(x_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1) 

#### Confusion Matrix

In [40]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class)) 
print(confusion_matrix(y_test_class,y_pred_class)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [41]:
(12+5+8)/30 

0.8333333333333334

In [42]:
(11+13+6)/30 

1.0